In [1]:
import pyspark
from pyspark.sql import SparkSession, Row

from pyspark.sql.types import MapType, StringType
from pyspark.sql.functions import col
from pyspark.sql.types import StructType, StructField, StringType

# Importación de datos desde Spark
# Conexión desde Python al servicio Spark donde se tiene la información.

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('LecturaArchivoCSV').getOrCreate()

parth_archivo = 'vgsales.csv'

df = spark.read.csv(parth_archivo,header=True)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/07/30 16:48:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 49670)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/Users/sarahivillegas/bigdata/spark/python/pyspark/accumulators.py", line 329, in handle
    poll(accum_updates)
    ~~~~^^^^^^^^^^^^^^^
  File "/Users/sarahivillegas/bigdata/spark/python/pyspark/accumulators.py", line 293, in poll
    if self.rfile.fileno() in r and func():
                                    ~~~~^^
  File "/Users/sarahivillegas/bigdata/spark/python/pyspark/accumulators.py", line 300, in accum_updates
    num_updates = read_int(self.rfile)
  File "/Users/sarahivillegas/bigdata/spark/python/pyspark/serializers.py", line 575, in read_int
    raise EOFError
EOFError
----------------------------------------

In [4]:
df.createOrReplaceTempView('VGSALES')
sql_str = 'select Publisher, sum(NA_Sales), sum(Global_Sales), sum(JP_Sales) from VGSALES group by Genre, Publisher order by Publisher desc'
spark.sql(sql_str).show()

+--------------------+-------------------+------------------+-------------+
|           Publisher|      sum(NA_Sales)| sum(Global_Sales)|sum(JP_Sales)|
+--------------------+-------------------+------------------+-------------+
|        responDESIGN|0.09000000000000001|              0.13|          0.0|
|           mixi, Inc|                0.0|              0.86|         0.86|
|inXile Entertainment|               0.02|               0.1|          0.0|
|     imageepoch Inc.|                0.0|              0.01|         0.01|
|     imageepoch Inc.|                0.0|              0.03|         0.03|
|         id Software|               0.02|              0.03|          0.0|
|                iWin|                0.0|              0.06|          0.0|
|              fonfun|                0.0|              0.02|         0.02|
|     dramatic create|                0.0|               0.1|          0.1|
|     dramatic create|                0.0|              0.01|         0.01|
|   bitComposer Games|                0.0|              0.03|          0.0|
|   bitComposer Games|               0.16|              0.38|          0.0|
|         Zushi Games|               0.04|              0.05|          0.0|
|         Zushi Games|               0.77|0.8699999999999999|          0.0|
|         Zushi Games|               0.08|              0.09|          0.0|
|         Zushi Games|               0.04|              0.05|          0.0|
|         Zushi Games|                0.1|              0.13|         0.01|
|         Zushi Games|               0.35|              0.37|          0.0|
|         Zushi Games|                0.0|              0.02|          0.0|
|         Zushi Games|               0.07|              0.07|          0.0|
+--------------------+-------------------+------------------+-------------+
only showing top 20 rows

In [5]:
df.show()

+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
|Rank|                Name|Platform|Year|       Genre|           Publisher|NA_Sales|EU_Sales|JP_Sales|Other_Sales|Global_Sales|
+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
|   1|          Wii Sports|     Wii|2006|      Sports|            Nintendo|   41.49|   29.02|    3.77|       8.46|       82.74|
|   2|   Super Mario Bros.|     NES|1985|    Platform|            Nintendo|   29.08|    3.58|    6.81|       0.77|       40.24|
|   3|      Mario Kart Wii|     Wii|2008|      Racing|            Nintendo|   15.85|   12.88|    3.79|       3.31|       35.82|
|   4|   Wii Sports Resort|     Wii|2009|      Sports|            Nintendo|   15.75|   11.01|    3.28|       2.96|          33|
|   5|Pokemon Red/Pokem...|      GB|1996|Role-Playing|            Nintendo|   11.27|    8.89|   10.22|          1|       31.37|
|   6|              Tetris|      GB|1989|      Puzzle|            Nintendo|    23.2|    2.26|    4.22|       0.58|       30.26|
|   7|New Super Mario B...|      DS|2006|    Platform|            Nintendo|   11.38|    9.23|     6.5|        2.9|       30.01|
|   8|            Wii Play|     Wii|2006|        Misc|            Nintendo|   14.03|     9.2|    2.93|       2.85|       29.02|
|   9|New Super Mario B...|     Wii|2009|    Platform|            Nintendo|   14.59|    7.06|     4.7|       2.26|       28.62|
|  10|           Duck Hunt|     NES|1984|     Shooter|            Nintendo|   26.93|    0.63|    0.28|       0.47|       28.31|
|  11|          Nintendogs|      DS|2005|  Simulation|            Nintendo|    9.07|      11|    1.93|       2.75|       24.76|
|  12|       Mario Kart DS|      DS|2005|      Racing|            Nintendo|    9.81|    7.57|    4.13|       1.92|       23.42|
|  13|Pokemon Gold/Poke...|      GB|1999|Role-Playing|            Nintendo|       9|    6.18|     7.2|       0.71|        23.1|
|  14|             Wii Fit|     Wii|2007|      Sports|            Nintendo|    8.94|    8.03|     3.6|       2.15|       22.72|
|  15|        Wii Fit Plus|     Wii|2009|      Sports|            Nintendo|    9.09|    8.59|    2.53|       1.79|          22|
|  16|  Kinect Adventures!|    X360|2010|        Misc|Microsoft Game St...|   14.97|    4.94|    0.24|       1.67|       21.82|
|  17|  Grand Theft Auto V|     PS3|2013|      Action|Take-Two Interactive|    7.01|    9.27|    0.97|       4.14|        21.4|
|  18|Grand Theft Auto:...|     PS2|2004|      Action|Take-Two Interactive|    9.43|     0.4|    0.41|      10.57|       20.81|
|  19|   Super Mario World|    SNES|1990|    Platform|            Nintendo|   12.78|    3.75|    3.54|       0.55|       20.61|
|  20|Brain Age: Train ...|      DS|2005|        Misc|            Nintendo|    4.75|    9.26|    4.16|       2.05|       20.22|
+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
only showing top 20 rows

In [6]:
df.count()

16598

In [7]:
df.createOrReplaceTempView('VGSALES')
sql_str = 'select Publisher, sum(NA_Sales), sum(Global_Sales), sum(JP_Sales) from VGSALES group by Genre, Publisher order by Publisher desc'
spark.sql(sql_str).show()

+--------------------+-------------------+------------------+-------------+
|           Publisher|      sum(NA_Sales)| sum(Global_Sales)|sum(JP_Sales)|
+--------------------+-------------------+------------------+-------------+
|        responDESIGN|0.09000000000000001|              0.13|          0.0|
|           mixi, Inc|                0.0|              0.86|         0.86|
|inXile Entertainment|               0.02|               0.1|          0.0|
|     imageepoch Inc.|                0.0|              0.01|         0.01|
|     imageepoch Inc.|                0.0|              0.03|         0.03|
|         id Software|               0.02|              0.03|          0.0|
|                iWin|                0.0|              0.06|          0.0|
|              fonfun|                0.0|              0.02|         0.02|
|     dramatic create|                0.0|               0.1|          0.1|
|     dramatic create|                0.0|              0.01|         0.01|
|   bitComposer Games|                0.0|              0.03|          0.0|
|   bitComposer Games|               0.16|              0.38|          0.0|
|         Zushi Games|               0.04|              0.05|          0.0|
|         Zushi Games|               0.77|0.8699999999999999|          0.0|
|         Zushi Games|               0.08|              0.09|          0.0|
|         Zushi Games|               0.04|              0.05|          0.0|
|         Zushi Games|                0.1|              0.13|         0.01|
|         Zushi Games|               0.35|              0.37|          0.0|
|         Zushi Games|                0.0|              0.02|          0.0|
|         Zushi Games|               0.07|              0.07|          0.0|
+--------------------+-------------------+------------------+-------------+
only showing top 20 rows

In [8]:
df.createOrReplaceTempView('VGSALES')
sql_str = 'select Publisher, round(sum(NA_Sales),2) as TotalNA, round(sum(Global_Sales),2) as TotalGlobal from VGSALES group by Publisher order by 3 desc'
spark.sql(sql_str).show(10,80)

+----------------------------+-------+-----------+
|                   Publisher|TotalNA|TotalGlobal|
+----------------------------+-------+-----------+
|                    Nintendo| 816.87|    1786.56|
|             Electronic Arts| 595.07|    1110.32|
|                  Activision|  429.7|     727.46|
| Sony Computer Entertainment| 265.22|      607.5|
|                     Ubisoft| 253.43|     474.72|
|        Take-Two Interactive| 220.49|     399.54|
|                         THQ| 208.77|     340.77|
|Konami Digital Entertainment|  92.16|     283.64|
|                        Sega|  109.4|     272.99|
|          Namco Bandai Games|  69.52|     254.09|
+----------------------------+-------+-----------+
only showing top 10 rows

In [9]:
spark.sql(sql_str).show(5,40)

+---------------------------+-------+-----------+
|                  Publisher|TotalNA|TotalGlobal|
+---------------------------+-------+-----------+
|                   Nintendo| 816.87|    1786.56|
|            Electronic Arts| 595.07|    1110.32|
|                 Activision|  429.7|     727.46|
|Sony Computer Entertainment| 265.22|      607.5|
|                    Ubisoft| 253.43|     474.72|
+---------------------------+-------+-----------+
only showing top 5 rows

In [10]:
spark.sql(sql_str).show(5,40,True)

-RECORD 0----------------------------------
 Publisher   | Nintendo
 TotalNA     | 816.87
 TotalGlobal | 1786.56
-RECORD 1----------------------------------
 Publisher   | Electronic Arts
 TotalNA     | 595.07
 TotalGlobal | 1110.32
-RECORD 2----------------------------------
 Publisher   | Activision
 TotalNA     | 429.7
 TotalGlobal | 727.46
-RECORD 3----------------------------------
 Publisher   | Sony Computer Entertainment
 TotalNA     | 265.22
 TotalGlobal | 607.5
-RECORD 4----------------------------------
 Publisher   | Ubisoft
 TotalNA     | 253.43
 TotalGlobal | 474.72
only showing top 5 rows

In [11]:
df.createOrReplaceTempView('VGSALES')
sql_str = 'select Publisher, round(sum(NA_Sales),2) as TotalNA, round(sum(Global_Sales),2) as TotalGlobal from VGSALES group by Publisher order by 3 desc'
spark.sql(sql_str).explain()

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- Sort [TotalGlobal#237 DESC NULLS LAST], true, 0
   +- Exchange rangepartitioning(TotalGlobal#237 DESC NULLS LAST, 200), ENSURE_REQUIREMENTS, [plan_id=322]
      +- HashAggregate(keys=[Publisher#22], functions=[sum(cast(NA_Sales#23 as double)), sum(cast(Global_Sales#27 as double))])
         +- Exchange hashpartitioning(Publisher#22, 200), ENSURE_REQUIREMENTS, [plan_id=319]
            +- HashAggregate(keys=[Publisher#22], functions=[partial_sum(cast(NA_Sales#23 as double)), partial_sum(cast(Global_Sales#27 as double))])
               +- FileScan csv [Publisher#22,NA_Sales#23,Global_Sales#27] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/Users/sarahivillegas/Github repositories/EBAC/Clases/Big Data II..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<Publisher:string,NA_Sales:string,Global_Sales:string>

In [12]:
spark.sql(sql_str).columns

['Publisher', 'TotalNA', 'TotalGlobal']

In [13]:
spark.sql(sql_str).count()

579

# Partición de datos

In [14]:
spark = SparkSession.builder.appName('Partitionby() PySpark').getOrCreate()

dataframe = spark.read.option('header',True).csv('vgsales.csv')

dataframe.printSchema()

root
 |-- Rank: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Platform: string (nullable = true)
 |-- Year: string (nullable = true)
 |-- Genre: string (nullable = true)
 |-- Publisher: string (nullable = true)
 |-- NA_Sales: string (nullable = true)
 |-- EU_Sales: string (nullable = true)
 |-- JP_Sales: string (nullable = true)
 |-- Other_Sales: string (nullable = true)
 |-- Global_Sales: string (nullable = true)

26/07/30 16:48:46 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [15]:
dataframe = dataframe.cache()
dataframe.count()   # Forces Spark to load the data

dataframe.write \
    .option("header", True) \
    .partitionBy("Platform") \
    .mode("overwrite") \
    .csv("partition/platform")

In [16]:
dataframe.write \
    .option("header", True) \
    .partitionBy("Year") \
    .mode("overwrite") \
    .csv("partition/year")

In [17]:
dataframe.write \
    .option("header", True) \
    .partitionBy("Genre",'Publisher') \
    .mode("overwrite") \
    .csv("partition/pub_genre")

In [18]:
dataframe.write \
    .option("header", True) \
    .partitionBy("Year",'Genre') \
    .mode("overwrite") \
    .csv("partition/year_genre")

In [19]:
dataframe.write \
    .option("header", True) \
    .option('maxRecordsPerFile',10) \
    .partitionBy("Genre") \
    .mode("overwrite") \
    .csv("partition/genre2")

In [20]:
dataframe.write \
    .option("header", True) \
    .option('maxRecordsPerFile',50) \
    .partitionBy("Genre") \
    .mode("overwrite") \
    .csv("partition/genre3")

# Coalesce y repartition

In [21]:
spark = SparkSession.builder.appName('coalesce() PySpark').getOrCreate()

dataco = spark.read.option('header',True).csv('vgsales.csv')

dataco.printSchema()

root
 |-- Rank: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Platform: string (nullable = true)
 |-- Year: string (nullable = true)
 |-- Genre: string (nullable = true)
 |-- Publisher: string (nullable = true)
 |-- NA_Sales: string (nullable = true)
 |-- EU_Sales: string (nullable = true)
 |-- JP_Sales: string (nullable = true)
 |-- Other_Sales: string (nullable = true)
 |-- Global_Sales: string (nullable = true)

26/07/30 17:00:40 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [22]:
dataco.count()

16598

In [23]:
dataco.repartition(20).write.mode('overwrite').option('header',True).csv('partition/rep')

In [24]:
dataco.repartition(30).write.mode('overwrite').option('header',True).csv('partition/rep')

In [25]:
dataco.repartition(10).write.mode('overwrite').option('header',True).csv('partition/ej10')

In [26]:
dataco.show()

+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
|Rank|                Name|Platform|Year|       Genre|           Publisher|NA_Sales|EU_Sales|JP_Sales|Other_Sales|Global_Sales|
+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
|   1|          Wii Sports|     Wii|2006|      Sports|            Nintendo|   41.49|   29.02|    3.77|       8.46|       82.74|
|   2|   Super Mario Bros.|     NES|1985|    Platform|            Nintendo|   29.08|    3.58|    6.81|       0.77|       40.24|
|   3|      Mario Kart Wii|     Wii|2008|      Racing|            Nintendo|   15.85|   12.88|    3.79|       3.31|       35.82|
|   4|   Wii Sports Resort|     Wii|2009|      Sports|            Nintendo|   15.75|   11.01|    3.28|       2.96|          33|
|   5|Pokemon Red/Pokem...|      GB|1996|Role-Playing|            Nintendo|   11.27|    8.89|   10.22|          1|       31.37|
|   6|              Tetris|      GB|1989|      Puzzle|            Nintendo|    23.2|    2.26|    4.22|       0.58|       30.26|
|   7|New Super Mario B...|      DS|2006|    Platform|            Nintendo|   11.38|    9.23|     6.5|        2.9|       30.01|
|   8|            Wii Play|     Wii|2006|        Misc|            Nintendo|   14.03|     9.2|    2.93|       2.85|       29.02|
|   9|New Super Mario B...|     Wii|2009|    Platform|            Nintendo|   14.59|    7.06|     4.7|       2.26|       28.62|
|  10|           Duck Hunt|     NES|1984|     Shooter|            Nintendo|   26.93|    0.63|    0.28|       0.47|       28.31|
|  11|          Nintendogs|      DS|2005|  Simulation|            Nintendo|    9.07|      11|    1.93|       2.75|       24.76|
|  12|       Mario Kart DS|      DS|2005|      Racing|            Nintendo|    9.81|    7.57|    4.13|       1.92|       23.42|
|  13|Pokemon Gold/Poke...|      GB|1999|Role-Playing|            Nintendo|       9|    6.18|     7.2|       0.71|        23.1|
|  14|             Wii Fit|     Wii|2007|      Sports|            Nintendo|    8.94|    8.03|     3.6|       2.15|       22.72|
|  15|        Wii Fit Plus|     Wii|2009|      Sports|            Nintendo|    9.09|    8.59|    2.53|       1.79|          22|
|  16|  Kinect Adventures!|    X360|2010|        Misc|Microsoft Game St...|   14.97|    4.94|    0.24|       1.67|       21.82|
|  17|  Grand Theft Auto V|     PS3|2013|      Action|Take-Two Interactive|    7.01|    9.27|    0.97|       4.14|        21.4|
|  18|Grand Theft Auto:...|     PS2|2004|      Action|Take-Two Interactive|    9.43|     0.4|    0.41|      10.57|       20.81|
|  19|   Super Mario World|    SNES|1990|    Platform|            Nintendo|   12.78|    3.75|    3.54|       0.55|       20.61|
|  20|Brain Age: Train ...|      DS|2005|        Misc|            Nintendo|    4.75|    9.26|    4.16|       2.05|       20.22|
+----+--------------------+--------+----+------------+--------------------+--------+--------+--------+-----------+------------+
only showing top 20 rows

In [27]:
dataco_2 = dataco.repartition(20)
dataco_2.rdd.getNumPartitions()

20

In [28]:
dataco_3 = dataco_2.coalesce(10)

In [29]:
dataco_3.write \
    .mode("overwrite") \
    .option("header", True) \
    .csv("partition/coalesce")

In [30]:
dataco_3.rdd.glom().collect()

[[Row(Rank='1619', Name='Farming Simulator 2015', Platform='PC', Year='2014', Genre='Simulation', Publisher='Focus Home Interactive', NA_Sales='0.08', EU_Sales='1.02', JP_Sales='0', Other_Sales='0.13', Global_Sales='1.23'),
  Row(Rank='5200', Name='NHL 2K10', Platform='Wii', Year='2009', Genre='Sports', Publisher='Take-Two Interactive', NA_Sales='0.33', EU_Sales='0.01', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.36'),
  Row(Rank='965', Name='Sonic Advance 2', Platform='GBA', Year='2002', Genre='Platform', Publisher='Sega', NA_Sales='0.93', EU_Sales='0.59', JP_Sales='0.21', Other_Sales='0.07', Global_Sales='1.8'),
  Row(Rank='8593', Name='California Speed', Platform='N64', Year='1999', Genre='Misc', Publisher='Midway Games', NA_Sales='0.13', EU_Sales='0.03', JP_Sales='0', Other_Sales='0', Global_Sales='0.16'),
  Row(Rank='4598', Name='Harry Potter and the Deathly Hallows - Part 1', Platform='DS', Year='2010', Genre='Action', Publisher='Electronic Arts', NA_Sales='0.2', EU_Sales='0.19', JP_Sales='0', Other_Sales='0.04', Global_Sales='0.42'),
  Row(Rank='2311', Name='Tiger Woods PGA Tour 12: The Masters', Platform='PS3', Year='2011', Genre='Sports', Publisher='Electronic Arts', NA_Sales='0.52', EU_Sales='0.26', JP_Sales='0', Other_Sales='0.12', Global_Sales='0.9'),
  Row(Rank='5990', Name='Punch-Out!!', Platform='Wii', Year='2007', Genre='Sports', Publisher='Nintendo', NA_Sales='0.02', EU_Sales='0.22', JP_Sales='0.05', Other_Sales='0', Global_Sales='0.29'),
  Row(Rank='4711', Name='X-Men: The Official Game', Platform='PS2', Year='2006', Genre='Action', Publisher='Activision', NA_Sales='0.2', EU_Sales='0.16', JP_Sales='0', Other_Sales='0.05', Global_Sales='0.41'),
  Row(Rank='1689', Name='Captain Toad: Treasure Tracker', Platform='WiiU', Year='2014', Genre='Puzzle', Publisher='Nintendo', NA_Sales='0.56', EU_Sales='0.36', JP_Sales='0.19', Other_Sales='0.09', Global_Sales='1.19'),
  Row(Rank='12818', Name='Tokyo Mono Harashi: Karasu no Mori Gakuen Kitan', Platform='PSP', Year='2010', Genre='Role-Playing', Publisher='Atlus', NA_Sales='0', EU_Sales='0', JP_Sales='0.06', Other_Sales='0', Global_Sales='0.06'),
  Row(Rank='6604', Name='Formula One 2001', Platform='PS2', Year='2001', Genre='Racing', Publisher='Sony Computer Entertainment', NA_Sales='0.13', EU_Sales='0.1', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.26'),
  Row(Rank='12176', Name='Mega Man: Battle & Chase', Platform='PS', Year='1997', Genre='Racing', Publisher='Capcom', NA_Sales='0', EU_Sales='0', JP_Sales='0.06', Other_Sales='0', Global_Sales='0.07'),
  Row(Rank='16553', Name='God Eater Off Shot: Tachibana Sakuya-hen Twin Pack & Animation Vol.7', Platform='PS4', Year='2016', Genre='Action', Publisher='Namco Bandai Games', NA_Sales='0', EU_Sales='0', JP_Sales='0.01', Other_Sales='0', Global_Sales='0.01'),
  Row(Rank='10564', Name="Surf's Up", Platform='X360', Year='2007', Genre='Sports', Publisher='Ubisoft', NA_Sales='0.09', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.1'),
  Row(Rank='7814', Name='Story of Seasons: Good Friends of the Three Villages', Platform='3DS', Year='2016', Genre='Simulation', Publisher='Marvelous Interactive', NA_Sales='0', EU_Sales='0', JP_Sales='0.19', Other_Sales='0', Global_Sales='0.19'),
  Row(Rank='8932', Name='Rayman Raving Rabbids', Platform='DS', Year='2007', Genre='Misc', Publisher='Ubisoft', NA_Sales='0.13', EU_Sales='0.01', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.15'),
  Row(Rank='12560', Name="Carol Vorderman's Sudoku", Platform='PSP', Year='2006', Genre='Puzzle', Publisher='Xplosiv', NA_Sales='0.05', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.06'),
  Row(Rank='4002', Name="Tony Hawk's Underground 2", Platform='GC', Year='2004', Genre='Sports', Publisher='Activision', NA_Sales='0.38', EU_Sales='0.1', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.5'),
  Row(Rank='355', Name='The Simpsons: Road Rage', Platform='PS2', Year='2001', Genre='Racing', Publisher='Electronic Arts', NA_Sales='2.02', EU_Sales='1.17', JP_Sales='0', Other_Sales='0.42', Global_Sales='3.61'),
  Row(Rank='3136', Name='Harry Potter and the Half-Blood Prince', Platform='PS2', Year='2009', Genre='Action', Publisher='Electronic Arts', NA_Sales='0.13', EU_Sales='0.07', JP_Sales='0', Other_Sales='0.44', Global_Sales='0.64'),
  Row(Rank='3809', Name='Oni', Platform='PS2', Year='2001', Genre='Action', Publisher='Take-Two Interactive', NA_Sales='0.26', EU_Sales='0.2', JP_Sales='0', Other_Sales='0.07', Global_Sales='0.53'),
  Row(Rank='16279', Name='Assetto Corsa', Platform='XOne', Year='2016', Genre='Racing', Publisher='505 Games', NA_Sales='0', EU_Sales='0.01', JP_Sales='0', Other_Sales='0', Global_Sales='0.01'),
  Row(Rank='15144', Name='Invizimals: The Lost Kingdom', Platform='PS3', Year='2013', Genre='Action', Publisher='Sony Computer Entertainment', NA_Sales='0', EU_Sales='0.02', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.02'),
  Row(Rank='7563', Name="Assassin's Creed Syndicate", Platform='PC', Year='2015', Genre='Action', Publisher='Ubisoft', NA_Sales='0.1', EU_Sales='0.08', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.2'),
  Row(Rank='16116', Name='Winning Post 7 Maximum 2008', Platform='PS3', Year='2008', Genre='Sports', Publisher='Tecmo Koei', NA_Sales='0', EU_Sales='0', JP_Sales='0.01', Other_Sales='0', Global_Sales='0.01'),
  Row(Rank='9754', Name='Puzzle Kingdoms', Platform='Wii', Year='2009', Genre='Puzzle', Publisher='Zoo Digital Publishing', NA_Sales='0.11', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.12'),
  Row(Rank='11646', Name="Infernal: Hell's Vengeance", Platform='X360', Year='2009', Genre='Shooter', Publisher='Playlogic Game Factory', NA_Sales='0.06', EU_Sales='0.01', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.08'),
  Row(Rank='14592', Name='Game of Thrones (Telltale)', Platform='XOne', Year='2015', Genre='Adventure', Publisher='Telltale Games', NA_Sales='0.03', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.03'),
  Row(Rank='4973', Name='Ice Age: Dawn of the Dinosaurs', Platform='DS', Year='2009', Genre='Action', Publisher='Activision', NA_Sales='0.2', EU_Sales='0.15', JP_Sales='0', Other_Sales='0.04', Global_Sales='0.39'),
  Row(Rank='14245', Name='Maximum Racing: GP Classic Racing', Platform='Wii', Year='2010', Genre='Racing', Publisher='Nordic Games', NA_Sales='0.03', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.03'),
  Row(Rank='8300', Name="The Lord of the Rings: Aragorn's Quest", Platform='PS3', Year='2010', Genre='Action', Publisher='Warner Bros. Interactive Entertainment', NA_Sales='0.1', EU_Sales='0.04', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.17'),
  Row(Rank='9712', Name='Are You Smarter than a 5th Grader? Game Time', Platform='X360', Year='2009', Genre='Puzzle', Publisher='THQ', NA_Sales='0.12', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.12'),
  Row(Rank='12530', Name="Foster's Home for Imaginary Friends: Imagination Invaders", Platform='DS', Year='2007', Genre='Adventure', Publisher='Midway Games', NA_Sales='0.06', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.06'),
  Row(Rank='6889', Name='Forsaken', Platform='PS', Year='1998', Genre='Shooter', Publisher='Acclaim Entertainment', NA_Sales='0.13', EU_Sales='0.09', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.24'),
  Row(Rank='10051', Name='World Championship Rugby', Platform='PS2', Year='2004', Genre='Sports', Publisher='Acclaim Entertainment', NA_Sales='0.06', EU_Sales='0.04', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.11'),
  Row(Rank='14883', Name='Drome Racers', Platform='GBA', Year='2003', Genre='Racing', Publisher='THQ', NA_Sales='0.02', EU_Sales='0.01', JP_Sales='0', Other_Sales='0', Global_Sales='0.03'),
  Row(Rank='14904', Name="Rock 'N' Roll Adventures", Platform='Wii', Year='2007', Genre='Platform', Publisher='Popcorn Arcade', NA_Sales='0.02', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.03'),
  Row(Rank='12120', Name='N+', Platform='DS', Year='2007', Genre='Platform', Publisher='Atari', NA_Sales='0.06', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.07'),
  Row(Rank='9040', Name='Iron & Blood', Platform='PS', Year='1996', Genre='Fighting', Publisher='Acclaim Entertainment', NA_Sales='0.08', EU_Sales='0.05', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.14'),
  Row(Rank='6434', Name='And1 Streetball', Platform='PS2', Year='2006', Genre='Action', Publisher='Ubisoft', NA_Sales='0.13', EU_Sales='0.1', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.27'),
  Row(Rank='13400', Name='Hiiro no Kakera DS', Platform='DS', Year='2008', Genre='Adventure', Publisher='Idea Factory', NA_Sales='0', EU_Sales='0', JP_Sales='0.05', Other_Sales='0', Global_Sales='0.05'),
  Row(Rank='5967', Name='X-Men Legends II: Rise of Apocalypse', Platform='PSP', Year='2005', Genre='Role-Playing', Publisher='Activision', NA_Sales='0.25', EU_Sales='0.01', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.29'),
  Row(Rank='4904', Name='Fire Emblem: Fuuin no Tsurugi', Platform='GBA', Year='2002', Genre='Role-Playing', Publisher='Nintendo', NA_Sales='0', EU_Sales='0', JP_Sales='0.39', Other_Sales='0', Global_Sales='0.39'),
  Row(Rank='501', Name='Call of Duty: Finest Hour', Platform='PS2', Year='2004', Genre='Shooter', Publisher='Activision', NA_Sales='1.51', EU_Sales='1.12', JP_Sales='0.01', Other_Sales='0.24', Global_Sales='2.89'),
  Row(Rank='15771', Name='Metal Fight Beyblade: Choujou Kessen! Big Bang Bladers', Platform='DS', Year='2010', Genre='Action', Publisher='Hudson Soft', NA_Sales='0', EU_Sales='0', JP_Sales='0.02', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='15517', Name='Triggerheart Excelica Enhanced', Platform='PS2', Year='2009', Genre='Shooter', Publisher='Alchemist', NA_Sales='0', EU_Sales='0', JP_Sales='0.02', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='3977', Name='Madden NFL 07', Platform='Wii', Year='2006', Genre='Sports', Publisher='Electronic Arts', NA_Sales='0.46', EU_Sales='0', JP_Sales='0', Other_Sales='0.04', Global_Sales='0.5'),
  Row(Rank='2443', Name='Rampage World Tour', Platform='PS', Year='1997', Genre='Action', Publisher='GT Interactive', NA_Sales='0.47', EU_Sales='0.32', JP_Sales='0', Other_Sales='0.06', Global_Sales='0.85'),
  Row(Rank='8676', Name='Arcade Zone', Platform='Wii', Year='2009', Genre='Misc', Publisher='Activision', NA_Sales='0.14', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.16'),
  Row(Rank='155', Name='Destiny', Platform='PS4', Year='2014', Genre='Shooter', Publisher='Activision', NA_Sales='2.49', EU_Sales='2.05', JP_Sales='0.16', Other_Sales='0.96', Global_Sales='5.65'),
  Row(Rank='9932', Name='Castlevania: Curse of Darkness', Platform='XB', Year='2005', Genre='Action', Publisher='Konami Digital Entertainment', NA_Sales='0.09', EU_Sales='0.03', JP_Sales='0', Other_Sales='0', Global_Sales='0.12'),
  Row(Rank='10186', Name='DualPenSports', Platform='3DS', Year='2011', Genre='Sports', Publisher='Namco Bandai Games', NA_Sales='0.05', EU_Sales='0.05', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.11'),
  Row(Rank='15415', Name='Puzzle City', Platform='DS', Year='2009', Genre='Puzzle', Publisher='Destineer', NA_Sales='0.02', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='8629', Name='Dynasty Warriors 8', Platform='X360', Year='2013', Genre='Action', Publisher='Tecmo Koei', NA_Sales='0.09', EU_Sales='0.05', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.16'),
  Row(Rank='3856', Name='Swing Away Golf', Platform='PS2', Year='2000', Genre='Sports', Publisher='Electronic Arts', NA_Sales='0.17', EU_Sales='0.13', JP_Sales='0.18', Other_Sales='0.04', Global_Sales='0.52'),
  Row(Rank='3255', Name='Tak 2: The Staff of Dreams', Platform='PS2', Year='2004', Genre='Platform', Publisher='THQ', NA_Sales='0.3', EU_Sales='0.24', JP_Sales='0', Other_Sales='0.08', Global_Sales='0.62'),
  Row(Rank='2564', Name='MadWorld', Platform='Wii', Year='2009', Genre='Action', Publisher='Sega', NA_Sales='0.46', EU_Sales='0.25', JP_Sales='0.02', Other_Sales='0.07', Global_Sales='0.8'),
  Row(Rank='14969', Name='Bus Simulator 16', Platform='PC', Year='2016', Genre='Simulation', Publisher='Astragon', NA_Sales='0', EU_Sales='0.02', JP_Sales='0', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='196', Name='Guitar Hero II', Platform='PS2', Year='2006', Genre='Misc', Publisher='RedOctane', NA_Sales='3.81', EU_Sales='0.63', JP_Sales='0', Other_Sales='0.68', Global_Sales='5.12'),
  Row(Rank='10833', Name='Darkest of Days', Platform='X360', Year='2009', Genre='Shooter', Publisher='Phantom EFX', NA_Sales='0.09', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.09'),
  Row(Rank='11361', Name='Petz: Dogz Family', Platform='PSP', Year='2009', Genre='Simulation', Publisher='Ubisoft', NA_Sales='0.05', EU_Sales='0.02', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.08'),
  Row(Rank='15986', Name='Dragon Zakura DS', Platform='DS', Year='2007', Genre='Misc', Publisher='Electronic Arts', NA_Sales='0', EU_Sales='0', JP_Sales='0.01', Other_Sales='0', Global_Sales='0.01'),
  Row(Rank='4098', Name='Millipede', Platform='2600', Year='1983', Genre='Shooter', Publisher='Atari', NA_Sales='0.45', EU_Sales='0.03', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.48'),
  Row(Rank='1481', Name='Corvette', Platform='PS2', Year='2004', Genre='Racing', Publisher='TDK Mediactive', NA_Sales='0.65', EU_Sales='0.51', JP_Sales='0', Other_Sales='0.17', Global_Sales='1.33'),
  Row(Rank='733', Name="Assassin's Creed IV: Black Flag", Platform='XOne', Year='2013', Genre='Action', Publisher='Ubisoft', NA_Sales='1.47', EU_Sales='0.55', JP_Sales='0', Other_Sales='0.19', Global_Sales='2.21'),
  Row(Rank='8085', Name='Ben 10 Ultimate Alien: Cosmic Destruction', Platform='X360', Year='2010', Genre='Platform', Publisher='D3Publisher', NA_Sales='0.1', EU_Sales='0.06', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.18'),
  Row(Rank='7361', Name='Hannah Montana: The Movie', Platform='X360', Year='2009', Genre='Adventure', Publisher='Disney Interactive Studios', NA_Sales='0.14', EU_Sales='0.06', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.21'),
  Row(Rank='4363', Name='One Piece: Pirate Warriors 3', Platform='PS4', Year='2015', Genre='Action', Publisher='Namco Bandai Games', NA_Sales='0.08', EU_Sales='0.22', JP_Sales='0.1', Other_Sales='0.05', Global_Sales='0.45'),
  Row(Rank='11242', Name='The Penguins of Madagascar: Dr. Blowhole Returns - Again!', Platform='PS3', Year='2011', Genre='Action', Publisher='THQ', NA_Sales='0.04', EU_Sales='0.03', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.09'),
  Row(Rank='5115', Name='High Heat Major League Baseball 2003', Platform='PS2', Year='2002', Genre='Sports', Publisher='3DO', NA_Sales='0.18', EU_Sales='0.14', JP_Sales='0', Other_Sales='0.05', Global_Sales='0.37'),
  Row(Rank='14327', Name='Togainu no Chi: True Blood', Platform='PS2', Year='2008', Genre='Adventure', Publisher='Kadokawa Shoten', NA_Sales='0', EU_Sales='0', JP_Sales='0.03', Other_Sales='0', Global_Sales='0.03'),
  Row(Rank='5429', Name='The Eye of Judgment', Platform='PS3', Year='2007', Genre='Misc', Publisher='Sony Computer Entertainment', NA_Sales='0.28', EU_Sales='0', JP_Sales='0.02', Other_Sales='0.03', Global_Sales='0.34'),
  Row(Rank='8358', Name='Solitaire Overload Plus', Platform='DS', Year='2010', Genre='Misc', Publisher='Telegames', NA_Sales='0.16', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.17'),
  Row(Rank='16268', Name='Myself; Yourself', Platform='PS2', Year='2007', Genre='Adventure', Publisher='Yeti', NA_Sales='0', EU_Sales='0', JP_Sales='0.01', Other_Sales='0', Global_Sales='0.01'),
  Row(Rank='7627', Name='NBA 07', Platform='PSP', Year='2006', Genre='Sports', Publisher='Sony Computer Entertainment', NA_Sales='0.18', EU_Sales='0', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.2'),
  Row(Rank='4705', Name="James Patterson Women's Murder Club: Games of Passion", Platform='DS', Year='2009', Genre='Adventure', Publisher='THQ', NA_Sales='0.15', EU_Sales='0.22', JP_Sales='0', Other_Sales='0.05', Global_Sales='0.41'),
  Row(Rank='10908', Name='echochrome', Platform='PSP', Year='2008', Genre='Puzzle', Publisher='Sony Computer Entertainment', NA_Sales='0', EU_Sales='0.01', JP_Sales='0.08', Other_Sales='0', Global_Sales='0.09'),
  Row(Rank='4954', Name='Fatal Fury', Platform='SNES', Year='1992', Genre='Fighting', Publisher='Takara', NA_Sales='0', EU_Sales='0', JP_Sales='0.39', Other_Sales='0', Global_Sales='0.39'),
  Row(Rank='9231', Name='MySims Collection', Platform='Wii', Year='2010', Genre='Misc', Publisher='Electronic Arts', NA_Sales='0.13', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.14'),
  Row(Rank='13246', Name='Crime Life: Gang Wars', Platform='XB', Year='2005', Genre='Action', Publisher='Konami Digital Entertainment', NA_Sales='0.04', EU_Sales='0.01', JP_Sales='0', Other_Sales='0', Global_Sales='0.05'),
  Row(Rank='6916', Name='Shadow Hearts: Covenant', Platform='PS2', Year='2004', Genre='Role-Playing', Publisher='Midway Games', NA_Sales='0.12', EU_Sales='0.09', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.24'),
  Row(Rank='9710', Name='Karaoke Revolution', Platform='X360', Year='2009', Genre='Misc', Publisher='Konami Digital Entertainment', NA_Sales='0.12', EU_Sales='0', JP_Sales='0', Other_Sales='0.01', Global_Sales='0.12'),
  Row(Rank='9288', Name='UEFA Euro 2004: Portugal', Platform='PS2', Year='2004', Genre='Sports', Publisher='Electronic Arts', NA_Sales='0.07', EU_Sales='0.05', JP_Sales='0', Other_Sales='0.02', Global_Sales='0.14'),
  Row(Rank='4773', Name='Knockout Kings 2001', Platform='PS', Year='2000', Genre='Fighting', Publisher='Electronic Arts', NA_Sales='0.23', EU_Sales='0.15', JP_Sales='0', Other_Sales='0.03', Global_Sales='0.41'),
  Row(Rank='15173', Name='Dream Chronicles', Platform='DS', Year='2010', Genre='Adventure', Publisher='Zoo Games', NA_Sales='0.02', EU_Sales='0', JP_Sales='0', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='11832', Name="Pong / Asteroids / Yars' Revenge", Platform='GBA', Year='2005', Genre='Misc', Publisher='Zoo Digital Publishing', NA_Sales='0.05', EU_Sales='0.02', JP_Sales='0', Other_Sales='0', Global_Sales='0.07'),
  Row(Rank='15279', Name='Kill.Switch', Platform='GBA', Year='2004', Genre='Shooter', Publisher='Zoo Digital Publishing', NA_Sales='0.02', EU_Sales='0.01', JP_Sales='0', Other_Sales='0', Global_Sales='0.02'),
  Row(Rank='324', Name='Mario & Sonic at the London 2012 Olympic Games', Platform='Wii', Year='2011', Genre='Sports', Publisher='Sega', NA_Sales='1.14', EU_Sales='1.91', JP_Sales='0.27', Other_Sales='0.46', Global_Sales='3.78'),
  Row(Rank='1298', Name='LittleBigPlanet PS Vita', Platform='PSV', Year='2012', Genre='Platform', Publisher='Sony Computer Entertainment', NA_Sales='0.4', EU_Sales='0.72', JP_Sales='0.02', Other_Sales='0.33', Global_Sales='1.47'),
  Row(Rank='19', Name='Super Mario World', Platform='SNES', Year='1990', Genre='Platform', Publisher='Nintendo', NA_Sales='12.78', EU_Sales='3.75', JP_Sales='3.54', Other_Sales='0.55', Global_Sales='20.61'),
  Row(Rank='13283', Name='Smash Court Tennis 3', Platform='PSP', Year='2007', Genre='Sports', Publisher='Namco Bandai Games', NA_Sales='0.01', EU_Sales='0.01', JP_Sales='0.01', Other_Sales='0.01', Global_Sales='0.05'),
  Row(Rank='13652', Name='7 Days to Die', Platform='XOne', Year='2016', Genre='Action', Publisher='Telltale Games', NA_Sales='0.02', EU_Sales='0.02', JP_Sales='0', Other_Sales='0', Global_Sales='0.04'),
  Row(Rank='15999', Name='Captain Morgane and the Golden Turtle', Platform='Wii', Year='2012', Genre='Adventure', Publisher='Reef Entertainment', NA_Sales='0', EU_Sales='0.01', JP_Sales='0', Other_Sales='0', Global_Sales='0.01'),

# PyArrow
### Big Data en Spark

In [31]:
from pyarrow import csv
import pyarrow as pa

In [32]:
archivo  = 'vgsales.csv'
tab_vgsales = csv.read_csv(archivo)

In [33]:
tab_vgsales

pyarrow.Table
Rank: int64
Name: string
Platform: string
Year: int64
Genre: string
Publisher: string
NA_Sales: double
EU_Sales: double
JP_Sales: double
Other_Sales: double
Global_Sales: double
----
Rank: [[1,2,3,4,5,...,12661,12662,12663,12664,12665],[12666,12667,12668,12669,12670,...,16596,16597,16598,16599,16600]]
Name: [["Wii Sports","Super Mario Bros.","Mario Kart Wii","Wii Sports Resort","Pokemon Red/Pokemon Blue",...,"Hajime no Ippo Portable: Victorious Spirits","Nanostray","CMT Presents: Karaoke Revolution Country","Katekyoo Hitman Reborn! DS: Flame Rumble Mukuro Kyoushuu","Cid to Chocobo no Fushigi na Dungeon: Toki Wasure no Meikyuu DS+"],["Vitamin X to Z","Fatal Frame","Flip's Twisted World","Tom Clancy's Ghost Recon: Advanced Warfighter","Urban Chaos: Riot Response",...,"Woody Woodpecker in Crazy Castle 5","Men in Black II: Alien Escape","SCORE International Baja 1000: The Official Game","Know How 2","Spirits & Spells"]]
Platform: [["Wii","NES","Wii","Wii","GB",...,"PSP","DS","PS2","DS","DS"],["PSP","XB","Wii","PS2","PS2",...,"GBA","GC","PS2","DS","GBA"]]
Year: [[2006,1985,2008,2009,1996,...,2007,2005,2006,2007,2008],[2011,2002,null,2006,2006,...,2002,2003,2008,2010,2003]]
Genre: [["Sports","Platform","Racing","Sports","Role-Playing",...,"Fighting","Shooter","Misc","Fighting","Role-Playing"],["Adventure","Action","Platform","Shooter","Shooter",...,"Platform","Shooter","Racing","Puzzle","Platform"]]
Publisher: [["Nintendo","Nintendo","Nintendo","Nintendo","Nintendo",...,"Grand Prix Games","Majesco Entertainment","Konami Digital Entertainment","Takara Tomy","Square Enix"],["D3Publisher","Tecmo Koei","Unknown","Ubisoft","Eidos Interactive",...,"Kemco","Infogrames","Activision","7G//AMES","Wanadoo"]]
NA_Sales: [[41.49,29.08,15.85,15.75,11.27,...,0,0.05,0.03,0,0],[0,0.04,0.05,0.03,0.03,...,0.01,0.01,0,0,0.01]]
EU_Sales: [[29.02,3.58,12.88,11.01,8.89,...,0,0,0.02,0,0],[0,0.01,0,0.02,0.02,...,0,0,0,0.01,0]]
JP_Sales: [[3.77,6.81,3.79,3.28,10.22,...,0.06,0,0,0.06,0.06],[0.06,0,0,0,0,...,0,0,0,0,0]]
Other_Sales: [[8.46,0.77,3.31,2.96,1,...,0,0,0.01,0,0],[0,0,0,0.01,0.01,...,0,0,0,0,0]]
...

In [34]:
len(tab_vgsales)

16598

In [35]:
tab_vgsales.column_names

['Rank',
 'Name',
 'Platform',
 'Year',
 'Genre',
 'Publisher',
 'NA_Sales',
 'EU_Sales',
 'JP_Sales',
 'Other_Sales',
 'Global_Sales']

In [36]:
tab_vgsales.schema

Rank: int64
Name: string
Platform: string
Year: int64
Genre: string
Publisher: string
NA_Sales: double
EU_Sales: double
JP_Sales: double
Other_Sales: double
Global_Sales: double

In [37]:
tab_vgsales.num_columns

11

In [38]:
tab_vgsales.num_rows

16598

In [39]:
df = tab_vgsales.to_pandas()

In [40]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [41]:
tab_vgsales

pyarrow.Table
Rank: int64
Name: string
Platform: string
Year: int64
Genre: string
Publisher: string
NA_Sales: double
EU_Sales: double
JP_Sales: double
Other_Sales: double
Global_Sales: double
----
Rank: [[1,2,3,4,5,...,12661,12662,12663,12664,12665],[12666,12667,12668,12669,12670,...,16596,16597,16598,16599,16600]]
Name: [["Wii Sports","Super Mario Bros.","Mario Kart Wii","Wii Sports Resort","Pokemon Red/Pokemon Blue",...,"Hajime no Ippo Portable: Victorious Spirits","Nanostray","CMT Presents: Karaoke Revolution Country","Katekyoo Hitman Reborn! DS: Flame Rumble Mukuro Kyoushuu","Cid to Chocobo no Fushigi na Dungeon: Toki Wasure no Meikyuu DS+"],["Vitamin X to Z","Fatal Frame","Flip's Twisted World","Tom Clancy's Ghost Recon: Advanced Warfighter","Urban Chaos: Riot Response",...,"Woody Woodpecker in Crazy Castle 5","Men in Black II: Alien Escape","SCORE International Baja 1000: The Official Game","Know How 2","Spirits & Spells"]]
Platform: [["Wii","NES","Wii","Wii","GB",...,"PSP","DS","PS2","DS","DS"],["PSP","XB","Wii","PS2","PS2",...,"GBA","GC","PS2","DS","GBA"]]
Year: [[2006,1985,2008,2009,1996,...,2007,2005,2006,2007,2008],[2011,2002,null,2006,2006,...,2002,2003,2008,2010,2003]]
Genre: [["Sports","Platform","Racing","Sports","Role-Playing",...,"Fighting","Shooter","Misc","Fighting","Role-Playing"],["Adventure","Action","Platform","Shooter","Shooter",...,"Platform","Shooter","Racing","Puzzle","Platform"]]
Publisher: [["Nintendo","Nintendo","Nintendo","Nintendo","Nintendo",...,"Grand Prix Games","Majesco Entertainment","Konami Digital Entertainment","Takara Tomy","Square Enix"],["D3Publisher","Tecmo Koei","Unknown","Ubisoft","Eidos Interactive",...,"Kemco","Infogrames","Activision","7G//AMES","Wanadoo"]]
NA_Sales: [[41.49,29.08,15.85,15.75,11.27,...,0,0.05,0.03,0,0],[0,0.04,0.05,0.03,0.03,...,0.01,0.01,0,0,0.01]]
EU_Sales: [[29.02,3.58,12.88,11.01,8.89,...,0,0,0.02,0,0],[0,0.01,0,0.02,0.02,...,0,0,0,0.01,0]]
JP_Sales: [[3.77,6.81,3.79,3.28,10.22,...,0.06,0,0,0.06,0.06],[0.06,0,0,0,0,...,0,0,0,0,0]]
Other_Sales: [[8.46,0.77,3.31,2.96,1,...,0,0,0.01,0,0],[0,0,0,0.01,0.01,...,0,0,0,0,0]]
...

In [43]:
type(tab_vgsales)

pyarrow.lib.Table

In [44]:
tab_genre = tab_vgsales.group_by('Genre').aggregate([('NA_Sales','sum')])

In [45]:
df1 = tab_genre.to_pandas()

In [46]:
df1.head()

          Genre  NA_Sales_sum
0        Sports        683.35
1      Platform        447.05
2        Racing        359.42
3  Role-Playing        327.28
4        Puzzle        123.78

In [47]:
tab2 = tab_vgsales.append_column('Test',pa.array(['0']*len(tab_vgsales),pa.string()))
df2 = tab2.to_pandas()
df2.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Test
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,0

In [48]:
tab2

pyarrow.Table
Rank: int64
Name: string
Platform: string
Year: int64
Genre: string
Publisher: string
NA_Sales: double
EU_Sales: double
JP_Sales: double
Other_Sales: double
Global_Sales: double
Test: string
----
Rank: [[1,2,3,4,5,...,12661,12662,12663,12664,12665],[12666,12667,12668,12669,12670,...,16596,16597,16598,16599,16600]]
Name: [["Wii Sports","Super Mario Bros.","Mario Kart Wii","Wii Sports Resort","Pokemon Red/Pokemon Blue",...,"Hajime no Ippo Portable: Victorious Spirits","Nanostray","CMT Presents: Karaoke Revolution Country","Katekyoo Hitman Reborn! DS: Flame Rumble Mukuro Kyoushuu","Cid to Chocobo no Fushigi na Dungeon: Toki Wasure no Meikyuu DS+"],["Vitamin X to Z","Fatal Frame","Flip's Twisted World","Tom Clancy's Ghost Recon: Advanced Warfighter","Urban Chaos: Riot Response",...,"Woody Woodpecker in Crazy Castle 5","Men in Black II: Alien Escape","SCORE International Baja 1000: The Official Game","Know How 2","Spirits & Spells"]]
Platform: [["Wii","NES","Wii","Wii","GB",...,"PSP","DS","PS2","DS","DS"],["PSP","XB","Wii","PS2","PS2",...,"GBA","GC","PS2","DS","GBA"]]
Year: [[2006,1985,2008,2009,1996,...,2007,2005,2006,2007,2008],[2011,2002,null,2006,2006,...,2002,2003,2008,2010,2003]]
Genre: [["Sports","Platform","Racing","Sports","Role-Playing",...,"Fighting","Shooter","Misc","Fighting","Role-Playing"],["Adventure","Action","Platform","Shooter","Shooter",...,"Platform","Shooter","Racing","Puzzle","Platform"]]
Publisher: [["Nintendo","Nintendo","Nintendo","Nintendo","Nintendo",...,"Grand Prix Games","Majesco Entertainment","Konami Digital Entertainment","Takara Tomy","Square Enix"],["D3Publisher","Tecmo Koei","Unknown","Ubisoft","Eidos Interactive",...,"Kemco","Infogrames","Activision","7G//AMES","Wanadoo"]]
NA_Sales: [[41.49,29.08,15.85,15.75,11.27,...,0,0.05,0.03,0,0],[0,0.04,0.05,0.03,0.03,...,0.01,0.01,0,0,0.01]]
EU_Sales: [[29.02,3.58,12.88,11.01,8.89,...,0,0,0.02,0,0],[0,0.01,0,0.02,0.02,...,0,0,0,0.01,0]]
JP_Sales: [[3.77,6.81,3.79,3.28,10.22,...,0.06,0,0,0.06,0.06],[0.06,0,0,0,0,...,0,0,0,0,0]]
Other_Sales: [[8.46,0.77,3.31,2.96,1,...,0,0,0.01,0,0],[0,0,0,0.01,0.01,...,0,0,0,0,0]]
...

# Uso de parquet

In [49]:
import pyarrow.parquet as pq
import pandas as pd
import pyarrow as pa

df = pd.DataFrame({'lin1':[-20,100,200],
                   'lin2':['este','es un','ejemplo'],
                   'l3':[False,True,True]},
                   index = list('abc'))

In [50]:
df

   lin1     lin2     l3
a   -20     este  False
b   100    es un   True
c   200  ejemplo   True

In [52]:
import os
import pyarrow as pa
import pyarrow.parquet as pq

# Create the directory if it doesn't exist
os.makedirs("parquet", exist_ok=True)

tab_example = pa.Table.from_pandas(df)
pq.write_table(tab_example, "parquet/ejemplo.parquet")

In [ ]:
import pyarrow.parquet as pq

table = pq.read_table("parquet/ejemplo.parquet")
print(table.schema)
print(table.to_pandas().head())

lin1: int64
lin2: string
l3: bool
__index_level_0__: string
-- schema metadata --
pandas: '{"index_columns": ["__index_level_0__"], "column_indexes": [{"na' + 644
   lin1     lin2     l3
a   -20     este  False
b   100    es un   True
c   200  ejemplo   True

26/07/30 19:43:04 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 1007505 ms exceeds timeout 120000 ms
26/07/30 19:43:04 WARN SparkContext: Killing executors is not supported by current scheduler.
26/07/30 19:43:07 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.1.8:49437
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/07/30 19:43:07 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:85)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:707)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1552)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:484)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1963)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.1.8:49437
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/07/30 19:43:16 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:34)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:707)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:706)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:746)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.1.8:49437
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:537)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:517)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:462)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:371)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:295)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/07/30 19:43:16 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:70)
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:44)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:359)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:85)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:707)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1552)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:484)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1963)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)