# PROYECTO: Prototipo de Delitos

Se seleccionó un archivo con los datos de enero, febrero y marzo de la página oficial, en formato CSV, para posteriormente crear una base de datos en SQL.

In [ ]:
#Se crea una función para quitar los acentos de la base de datos, ya que MySQL Workbench solo acepta archivos en formato UTF-8.

import pandas as pd
import unicodedata

def quitar_acentos(texto):
    if isinstance(texto, str):
        texto = unicodedata.normalize('NFKD', texto)
        return ''.join(c for c in texto if not unicodedata.combining(c))
    return texto

#leer el archivo csv
df = pd.read_csv('delitos.csv')

#las columnas del dataframe
columnas = df.columns.tolist()

#quitar los acentos a cada columna y a los nombres de las columnas
for col in columnas:
    df[col] = df[col].apply(quitar_acentos)

df.columns = [quitar_acentos(col) for col in df.columns]

columns = ['Ano','Clave_Ent','Entidad','Bien juridico afectado', 'Tipo de delito','Subtipo de delito','Modalidad','Enero','Febrero','Marzo']

df = df[columns]

df.sample(3)

#df.to_csv('output.csv')

,Ano,Clave_Ent,Entidad,Bien juridico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo
821,2026,8,Chihuahua,La vida y la Integridad corporal,Feminicidio,Feminicidio,No especificado,0,0,3
3307,2026,30,Veracruz de Ignacio de la Llave,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,50,48,55
1520,2026,14,Jalisco,La libertad y la seguridad sexual,Hostigamiento sexual,Hostigamiento sexual,Hostigamiento sexual,5,9,11

In [ ]:
# columnas que NO se transforman

id_vars = ['Ano','Clave_Ent','Entidad','Bien juridico afectado', 'Tipo de delito','Subtipo de delito','Modalidad']

df_largo = df.melt(
    id_vars=id_vars,
    value_vars=['Enero', 'Febrero', 'Marzo'],
    var_name='Mes',
    value_name='Total_delitos'
)

df_largo.sample(3)

,Ano,Clave_Ent,Entidad,Bien juridico afectado,Tipo de delito,Subtipo de delito,Modalidad,Mes,Total_delitos
3032,2026,27,Tabasco,El patrimonio,Robo,Robo a negocio,Con violencia,Enero,106
8590,2026,12,Guerrero,La libertad y la seguridad sexual,Violacion,Violacion simple,Violacion simple,Marzo,21
2641,2026,24,San Luis Potosi,La vida y la Integridad corporal,Lesiones,Lesiones culposas,No especificado,Enero,0

In [69]:
df_largo['Ano_mes'] = df_largo['Ano'].astype(str) + '-' + df_largo['Mes']
df_largo.sample(3)
df_largo.to_csv('output.csv')

## Conexión a la base de datos
Crea un cursor desde Python que permite conectarse y hacer consultas o querys a la base de datos previamente creada.

In [ ]:
import mysql.connector

# Crear conexión
conexion = mysql.connector.connect(
    host="localhost",      
    user="root",
    password="Root123$",
    database="PROYECTO_DELITOS"
)

# Crear cursor
cursor = conexion.cursor()

# Ejecutar una consulta
query = "SELECT * FROM delitos LIMIT 10;"
cursor.execute(query)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio doloso', 'Con arma blanca', 'Enero', 1, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio doloso', 'Con arma de fuego', 'Enero', 4, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio doloso', 'Con otro elemento', 'Enero', 0, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio doloso', 'No especificado', 'Enero', 0, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Tentativa de homicidio doloso', 'Tentativa de homicidio doloso', 'Enero', 1, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio culposo', 'Con arma blanca', 'Enero', 0, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio culposo', 'Con arma de fuego', 'Enero', 0, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio culposo', 'Con otro elemento', 'Enero', 0, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio culposo', 'En accidente de transito', 'Enero', 10, '2026-Enero')
(2026, 1, 'Aguascalientes', 'La vida y la Integridad corporal', 'Homicidio', 'Homicidio culposo', 'No especificado', 'Enero', 1, '2026-Enero')

In [ ]:
#(a)  Número promedio de delitos agrupados por municipio y año-mes de ocurrencia de estos. 
# Ejecutar una consulta
query1 = """
SELECT Entidad, Ano_mes, AVG(Total_delitos) as Promedio_delitos
FROM delitos
GROUP BY Entidad, Ano_mes
ORDER BY Entidad, Ano_mes
"""
cursor.execute(query1)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

('Aguascalientes', '2026-Enero', Decimal('28.3246'))
('Aguascalientes', '2026-Febrero', Decimal('26.7632'))
('Aguascalientes', '2026-Marzo', Decimal('31.5789'))
('Baja California', '2026-Enero', Decimal('62.1842'))
('Baja California', '2026-Febrero', Decimal('60.3596'))
('Baja California', '2026-Marzo', Decimal('72.2632'))
('Baja California Sur', '2026-Enero', Decimal('16.1491'))
('Baja California Sur', '2026-Febrero', Decimal('15.2368'))
('Baja California Sur', '2026-Marzo', Decimal('17.7281'))
('Campeche', '2026-Enero', Decimal('3.0614'))
('Campeche', '2026-Febrero', Decimal('2.9211'))
('Campeche', '2026-Marzo', Decimal('3.4825'))
('Chiapas', '2026-Enero', Decimal('5.7105'))
('Chiapas', '2026-Febrero', Decimal('6.2982'))
('Chiapas', '2026-Marzo', Decimal('7.1404'))
('Chihuahua', '2026-Enero', Decimal('45.7982'))
('Chihuahua', '2026-Febrero', Decimal('47.3860'))
('Chihuahua', '2026-Marzo', Decimal('58.1404'))
('Ciudad de Mexico', '2026-Enero', Decimal('141.5351'))
('Ciudad de Mexico', '2026-Febrero', Decimal('138.1930'))
('Ciudad de Mexico', '2026-Marzo', Decimal('155.5702'))
('Coahuila de Zaragoza', '2026-Enero', Decimal('45.0526'))
('Coahuila de Zaragoza', '2026-Febrero', Decimal('49.0965'))
('Coahuila de Zaragoza', '2026-Marzo', Decimal('55.5351'))
('Colima', '2026-Enero', Decimal('19.3421'))
('Colima', '2026-Febrero', Decimal('18.8596'))
('Colima', '2026-Marzo', Decimal('21.4474'))
('Durango', '2026-Enero', Decimal('12.9035'))
('Durango', '2026-Febrero', Decimal('13.0789'))
('Durango', '2026-Marzo', Decimal('13.2018'))
('Guanajuato', '2026-Enero', Decimal('106.2105'))
('Guanajuato', '2026-Febrero', Decimal('102.0175'))
('Guanajuato', '2026-Marzo', Decimal('124.0263'))
('Guerrero', '2026-Enero', Decimal('18.1053'))
('Guerrero', '2026-Febrero', Decimal('16.5789'))
('Guerrero', '2026-Marzo', Decimal('20.4649'))
('Hidalgo', '2026-Enero', Decimal('36.3860'))
('Hidalgo', '2026-Febrero', Decimal('36.2982'))
('Hidalgo', '2026-Marzo', Decimal('42.3509'))
('Jalisco', '2026-Enero', Decimal('75.8246'))
('Jalisco', '2026-Febrero', Decimal('71.7105'))
('Jalisco', '2026-Marzo', Decimal('89.5263'))
('Mexico', '2026-Enero', Decimal('248.4035'))
('Mexico', '2026-Febrero', Decimal('225.5702'))
('Mexico', '2026-Marzo', Decimal('241.4649'))
('Michoacan de Ocampo', '2026-Enero', Decimal('34.3421'))
('Michoacan de Ocampo', '2026-Febrero', Decimal('35.3772'))
('Michoacan de Ocampo', '2026-Marzo', Decimal('39.4298'))
('Morelos', '2026-Enero', Decimal('33.3947'))
('Morelos', '2026-Febrero', Decimal('31.1228'))
('Morelos', '2026-Marzo', Decimal('37.0877'))
('Nayarit', '2026-Enero', Decimal('8.0702'))
('Nayarit', '2026-Febrero', Decimal('7.5439'))
('Nayarit', '2026-Marzo', Decimal('6.3772'))
('Nuevo Leon', '2026-Enero', Decimal('42.8421'))
('Nuevo Leon', '2026-Febrero', Decimal('43.5702'))
('Nuevo Leon', '2026-Marzo', Decimal('61.8421'))
('Oaxaca', '2026-Enero', Decimal('19.1930'))
('Oaxaca', '2026-Febrero', Decimal('19.3333'))
('Oaxaca', '2026-Marzo', Decimal('19.8333'))
('Puebla', '2026-Enero', Decimal('56.3421'))
('Puebla', '2026-Febrero', Decimal('53.2281'))
('Puebla', '2026-Marzo', Decimal('65.1754'))
('Queretaro', '2026-Enero', Decimal('40.7544'))
('Queretaro', '2026-Febrero', Decimal('39.1053'))
('Queretaro', '2026-Marzo', Decimal('45.2544'))
('Quintana Roo', '2026-Enero', Decimal('41.4737'))
('Quintana Roo', '2026-Febrero', Decimal('38.2193'))
('Quintana Roo', '2026-Marzo', Decimal('46.6579'))
('San Luis Potosi', '2026-Enero', Decimal('41.1140'))
('San Luis Potosi', '2026-Febrero', Decimal('39.9386'))
('San Luis Potosi', '2026-Marzo', Decimal('42.6404'))
('Sinaloa', '2026-Enero', Decimal('26.1053'))
('Sinaloa', '2026-Febrero', Decimal('27.5175'))
('Sinaloa', '2026-Marzo', Decimal('31.6140'))
('Sonora', '2026-Enero', Decimal('18.3246'))
('Sonora', '2026-Febrero', Decimal('21.5702'))
('Sonora', '2026-Marzo', Decimal('27.5702'))
('Tabasco', '2026-Enero', Decimal('29.9561'))
('Tabasco', '2026-Febrero', Decimal('30.7368'))
('Tabasco', '2026-Marzo', Decimal('36.0439'))
('Tamaulipas', '2026-Enero', Decimal('25.6667'))
('Tamaulipas', '2026-Febrero', Decimal('27.3596'))
('Tamaulipas', '2026-Marzo', Decimal('32.4035'))
('Tlaxcala', '2026-Enero', Decimal('1.1316'))
('Tlaxcala', '2026-Febrero', Decimal('1.3596'))
('Tlaxcala', '2026-Marzo', Decimal('1.3772'))
('Veracruz de Ignacio de la Llave', '2026-Enero', Decimal('54.4211'))
('Veracruz de Ignacio de la Llave', '2026-Febrero', Decimal('53.5789'))
('Veracruz de Ignacio de la Llave', '2026-Marzo', Decimal('66.3333'))
('Yucatan', '2026-Enero', Decimal('4.9298'))
('Yucatan', '2026-Febrero', Decimal('5.0789'))
('Yucatan', '2026-Marzo', Decimal('5.1842'))
('Zacatecas', '2026-Enero', Decimal('14.9474'))
('Zacatecas', '2026-Febrero', Decimal('15.9737'))
('Zacatecas', '2026-Marzo', Decimal('18.5263'))

In [35]:
#(b)   El delito más común por municipio
# Ejecutar una consulta
query2 = """
SELECT 
    Entidad,
    `Tipo de delito`,
    Total_Delitos
FROM (
    SELECT 
        Entidad,
        `Tipo de delito`,
        SUM(Total_delitos) AS Total_Delitos,
        RANK() OVER (
            PARTITION BY Entidad
            ORDER BY SUM(Total_delitos) DESC
        ) AS ranking
    FROM delitos
    GROUP BY Entidad, `Tipo de delito`
) AS subconsulta
WHERE ranking = 1;
"""
cursor.execute(query2)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

('Aguascalientes', 'Robo', Decimal('2075'))
('Baja California', 'Robo', Decimal('5664'))
('Baja California Sur', 'Robo', Decimal('1088'))
('Campeche', 'Lesiones', Decimal('179'))
('Chiapas', 'Narcomenudeo', Decimal('351'))
('Chihuahua', 'Violencia familiar', Decimal('3180'))
('Ciudad de Mexico', 'Robo', Decimal('13968'))
('Coahuila de Zaragoza', 'Amenazas', Decimal('3678'))
('Colima', 'Violencia familiar', Decimal('1063'))
('Durango', 'Violencia familiar', Decimal('1191'))
('Guanajuato', 'Robo', Decimal('6861'))
('Guerrero', 'Robo', Decimal('1225'))
('Hidalgo', 'Robo', Decimal('2923'))
('Jalisco', 'Robo', Decimal('7196'))
('Mexico', 'Robo', Decimal('20893'))
('Michoacan de Ocampo', 'Robo', Decimal('2761'))
('Morelos', 'Robo', Decimal('2892'))
('Nayarit', 'Violencia familiar', Decimal('344'))
('Nuevo Leon', 'Violencia familiar', Decimal('3569'))
('Oaxaca', 'Robo', Decimal('1135'))
('Puebla', 'Robo', Decimal('7568'))
('Queretaro', 'Robo', Decimal('4356'))
('Quintana Roo', 'Robo', Decimal('2801'))
('San Luis Potosi', 'Narcomenudeo', Decimal('2938'))
('Sinaloa', 'Robo', Decimal('2587'))
('Sonora', 'Narcomenudeo', Decimal('1645'))
('Tabasco', 'Robo', Decimal('2052'))
('Tamaulipas', 'Robo', Decimal('1950'))
('Tlaxcala', 'Robo', Decimal('220'))
('Veracruz de Ignacio de la Llave', 'Robo', Decimal('4160'))
('Yucatan', 'Dano a la propiedad', Decimal('344'))
('Zacatecas', 'Robo', Decimal('1161'))

In [43]:
#(c)   La temporada con más crímenes en México
# Ejecutar una consulta
query3 = """
SELECT 
    Ano_mes,
    SUM(Total_delitos) AS Total_Delitos
FROM delitos
GROUP BY Ano_mes
ORDER BY Ano_mes DESC
LIMIT 1;
"""
cursor.execute(query3)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

('2026-Marzo', Decimal('175249'))

In [45]:
#(d)  El número promedio de delitos agrupados por tipo de delito y año y mes en la ciudad de México ordenados de mayor a menor
# Ejecutar una consulta
query3 = """
SELECT 
    `Tipo de delito`,
    Ano_mes,
    AVG(Total_delitos) AS Promedio_delitos
FROM delitos
GROUP BY `Tipo de delito`, Ano_mes
ORDER BY AVG(Total_delitos) DESC

"""
cursor.execute(query3)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

('Violencia familiar', '2026-Marzo', Decimal('746.7188'))
('Violencia familiar', '2026-Febrero', Decimal('603.6250'))
('Violencia familiar', '2026-Enero', Decimal('587.7188'))
('Otros delitos del Fuero Comun', '2026-Enero', Decimal('485.6563'))
('Otros delitos del Fuero Comun', '2026-Marzo', Decimal('457.0000'))
('Otros delitos del Fuero Comun', '2026-Febrero', Decimal('437.3750'))
('Amenazas', '2026-Marzo', Decimal('415.5938'))
('Dano a la propiedad', '2026-Marzo', Decimal('391.8125'))
('Dano a la propiedad', '2026-Enero', Decimal('348.6875'))
('Dano a la propiedad', '2026-Febrero', Decimal('337.9375'))
('Amenazas', '2026-Febrero', Decimal('334.3125'))
('Amenazas', '2026-Enero', Decimal('325.8125'))
('Fraude', '2026-Marzo', Decimal('318.3125'))
('Fraude', '2026-Enero', Decimal('293.6563'))
('Fraude', '2026-Febrero', Decimal('285.0625'))
('Narcomenudeo', '2026-Marzo', Decimal('139.0313'))
('Narcomenudeo', '2026-Enero', Decimal('126.4375'))
('Narcomenudeo', '2026-Febrero', Decimal('125.3125'))
('Abuso sexual', '2026-Marzo', Decimal('96.4063'))
('Incumplimiento de obligaciones de asistencia familiar', '2026-Marzo', Decimal('82.6875'))
('Despojo', '2026-Marzo', Decimal('82.5625'))
('Abuso de confianza', '2026-Marzo', Decimal('80.1563'))
('Abuso sexual', '2026-Febrero', Decimal('77.3750'))
('Incumplimiento de obligaciones de asistencia familiar', '2026-Febrero', Decimal('73.1250'))
('Despojo', '2026-Febrero', Decimal('71.3750'))
('Abuso de confianza', '2026-Enero', Decimal('70.9063'))
('Abuso sexual', '2026-Enero', Decimal('70.5625'))
('Abuso de confianza', '2026-Febrero', Decimal('70.4688'))
('Incumplimiento de obligaciones de asistencia familiar', '2026-Enero', Decimal('67.5000'))
('Despojo', '2026-Enero', Decimal('67.3750'))
('Lesiones', '2026-Marzo', Decimal('66.9410'))
('Delitos cometidos por servidores publicos', '2026-Marzo', Decimal('56.3438'))
('Lesiones', '2026-Febrero', Decimal('55.2708'))
('Lesiones', '2026-Enero', Decimal('54.9826'))
('Suplantacion y usurpacion de identidad', '2026-Marzo', Decimal('52.9063'))
('Suplantacion y usurpacion de identidad', '2026-Enero', Decimal('49.2188'))
('Delitos cometidos por servidores publicos', '2026-Febrero', Decimal('47.0938'))
('Otros delitos contra el patrimonio', '2026-Enero', Decimal('45.8750'))
('Otros delitos contra el patrimonio', '2026-Marzo', Decimal('45.7500'))
('Otros delitos contra el patrimonio', '2026-Febrero', Decimal('45.5625'))
('Delitos cometidos por servidores publicos', '2026-Enero', Decimal('44.5938'))
('Suplantacion y usurpacion de identidad', '2026-Febrero', Decimal('40.9688'))
('Falsificacion', '2026-Marzo', Decimal('39.0938'))
('Retencion o sustraccion de menores e incapaces', '2026-Marzo', Decimal('36.5938'))
('Allanamiento de morada', '2026-Marzo', Decimal('36.2813'))
('Allanamiento de morada', '2026-Febrero', Decimal('34.4688'))
('Allanamiento de morada', '2026-Enero', Decimal('34.0000'))
('Otros delitos contra la familia', '2026-Marzo', Decimal('33.7500'))
('Retencion o sustraccion de menores e incapaces', '2026-Enero', Decimal('32.8750'))
('Falsificacion', '2026-Febrero', Decimal('32.4375'))
('Robo', '2026-Marzo', Decimal('32.1563'))
('Robo', '2026-Enero', Decimal('32.0946'))
('Acoso sexual', '2026-Marzo', Decimal('31.2188'))
('Retencion o sustraccion de menores e incapaces', '2026-Febrero', Decimal('30.3125'))
('Falsificacion', '2026-Enero', Decimal('29.4063'))
('Violacion', '2026-Marzo', Decimal('28.9219'))
('Robo', '2026-Febrero', Decimal('28.7682'))
('Otros delitos que atentan contra la libertad personal', '2026-Marzo', Decimal('27.5625'))
('Privacion ilegal de la libertad', '2026-Marzo', Decimal('25.6563'))
('Otros delitos que atentan contra la libertad y la seguridad sexual', '2026-Marzo', Decimal('25.0000'))
('Acoso sexual', '2026-Febrero', Decimal('24.6875'))
('Violacion', '2026-Febrero', Decimal('22.7188'))
('Otros delitos que atentan contra la libertad y la seguridad sexual', '2026-Enero', Decimal('22.6875'))
('Otros delitos que atentan contra la libertad personal', '2026-Enero', Decimal('22.5000'))
('Acoso sexual', '2026-Enero', Decimal('22.3750'))
('Otros delitos contra la familia', '2026-Febrero', Decimal('22.0313'))
('Privacion ilegal de la libertad', '2026-Enero', Decimal('21.9688'))
('Otros delitos que atentan contra la libertad y la seguridad sexual', '2026-Febrero', Decimal('21.6250'))
('Violacion a la intimidad sexual', '2026-Marzo', Decimal('21.5625'))
('Violacion', '2026-Enero', Decimal('21.2188'))
('Otros delitos contra la sociedad', '2026-Marzo', Decimal('20.6875'))
('Otros delitos que atentan contra la vida y la integridad corporal', '2026-Marzo', Decimal('20.5938'))
('Otros delitos que atentan contra la libertad personal', '2026-Febrero', Decimal('20.3438'))
('Otros delitos que atentan contra la vida y la integridad corporal', '2026-Enero', Decimal('20.0000'))
('Otros delitos que atentan contra la vida y la integridad corporal', '2026-Febrero', Decimal('19.6875'))
('Otros delitos contra la sociedad', '2026-Febrero', Decimal('19.5625'))
('Privacion ilegal de la libertad', '2026-Febrero', Decimal('19.4063'))
('Otros delitos contra la familia', '2026-Enero', Decimal('18.9063'))
('Delitos contra la administracion de justicia', '2026-Marzo', Decimal('16.8438'))
('Violacion a la intimidad sexual', '2026-Enero', Decimal('15.9375'))
('Falsedad', '2026-Marzo', Decimal('15.8750'))
('Violacion a la intimidad sexual', '2026-Febrero', Decimal('15.7813'))
('Violencia de genero en todas sus modalidades distinta a la violencia familiar', '2026-Marzo', Decimal('14.0313'))
('Otros delitos contra la sociedad', '2026-Enero', Decimal('13.9688'))
('Falsedad', '2026-Febrero', Decimal('12.2500'))
('Violencia de genero en todas sus modalidades distinta a la violencia familiar', '2026-Febrero', Decimal('10.8125'))
('Discriminacion', '2026-Marzo', Decimal('10.6250'))
('Corrupcion de menores', '2026-Marzo', Decimal('10.4688'))
('Delitos contra la administracion de justicia', '2026-Febrero', Decimal('10.0000'))
('Violencia de genero en todas sus modalidades distinta a la violencia familiar', '2026-Enero', Decimal('9.9688'))
('Delitos contra la administracion de justicia', '2026-Enero', Decimal('9.7813'))
('Contra el medio ambiente', '2026-Marzo', Decimal('9.5938'))
('Homicidio', '2026-Marzo', Decimal('9.5156'))
('Falsedad', '2026-Enero', Decimal('9.4688'))
('Extorsion', '2026-Marzo', Decimal('9.2344'))
('Contra el medio ambiente', '2026-Febrero', Decimal('9.0938'))
('Homicidio', '2026-Enero', Decimal('8.6719'))
('Tortura', '2026-Marzo', Decimal('8.6563'))
('Homicidio', '2026-Febrero', Decimal('8.4938'))
('Hostigamiento sexual', '2026-Febrero', Decimal('7.9063'))
('Corrupcion de menores', '2026-Febrero', Decimal('7.8750'))
('Discriminacion', '2026-Febrero', Decimal('7.4375'))
('Hostigamiento sexual', '2026-Enero', Decimal('7.1875'))
('Discriminacion', '2026-Enero', Decimal('6.6563'))
('Corrupcion de menores', '2026-Enero', Decimal('6.5313'))
('Extorsion', '2026-Febrero', Decimal('6.5234'))
('Contra el medio ambiente', '2026-Enero', Decimal('6.4063'))
('Extorsion', '2026-Enero', Decimal('5.9219'))
('Hostigamiento sexual', '2026-Marzo', Decimal('5.7813'))
('Tortura', '2026-Febrero', Decimal('5.2813'))
('Tortura', '2026-Enero', Decimal('4.7188'))
('Aborto', '2026-Marzo', Decimal('2.6875'))
('Aborto', '2026-Febrero', Decimal('2.1250'))
('Aborto', '2026-Enero', Decimal('1.8750'))
('Electorales', '2026-Febrero', Decimal('1.3125'))
('Pornografia infantil', '2026-Marzo', Decimal('1.0313'))
('Electorales', '2026-Marzo', Decimal('1.0313'))
('Pornografia infantil', '2026-Febrero', Decimal('0.9063'))
('Electorales', '2026-Enero', Decimal('0.8750'))
('Feminicidio', '2026-Marzo', Decimal('0.8000'))
('Pornografia infantil', '2026-Enero', Decimal('0.6563'))
('Evasion de presos', '2026-Febrero', Decimal('0.6250'))
('Evasion de presos', '2026-Enero', Decimal('0.5938'))
('Feminicidio', '2026-Enero', Decimal('0.5500'))
('Evasion de presos', '2026-Marzo', Decimal('0.5000'))
('Trata de personas', '2026-Febrero', Decimal('0.4844'))
('Feminicidio', '2026-Febrero', Decimal('0.4688'))
('Trata de personas', '2026-Marzo', Decimal('0.4063'))
('Trata de personas', '2026-Enero', Decimal('0.3281'))
('Secuestro', '2026-Marzo', Decimal('0.3281'))
('Secuestro', '2026-Febrero', Decimal('0.3125'))
('Secuestro', '2026-Enero', Decimal('0.2109'))
('Rapto', '2026-Enero', Decimal('0.0938'))
('Rapto', '2026-Marzo', Decimal('0.0938'))
('Rapto', '2026-Febrero', Decimal('0.0313'))
('Incesto', '2026-Marzo', Decimal('0.0313'))
('Trafico de menores', '2026-Enero', Decimal('0.0000'))
('Incesto', '2026-Enero', Decimal('0.0000'))
('Trafico de menores', '2026-Febrero', Decimal('0.0000'))
('Incesto', '2026-Febrero', Decimal('0.0000'))
('Trafico de menores', '2026-Marzo', Decimal('0.0000'))

In [47]:
#(d)  El número promedio de delitos agrupados por tipo de delito y año y mes en la ciudad de México ordenados de mayor a menor
# Ejecutar una consulta
query4 = """
SELECT 
    `Tipo de delito`,
    SUM(Total_delitos) AS Tota_Delitos
FROM delitos
GROUP BY `Tipo de delito`
ORDER BY SUM(Total_delitos) DESC

"""
cursor.execute(query4)


# Obtener resultados
resultados = cursor.fetchall()

# Mostrar resultados
for fila in resultados:
    print(fila)

('Robo', Decimal('107158'))
('Violencia familiar', Decimal('62018'))
('Lesiones', Decimal('51032'))
('Otros delitos del Fuero Comun', Decimal('44161'))
('Dano a la propiedad', Decimal('34510'))
('Amenazas', Decimal('34423'))
('Fraude', Decimal('28705'))
('Narcomenudeo', Decimal('25010'))
('Homicidio', Decimal('8538'))
('Abuso sexual', Decimal('7819'))
('Incumplimiento de obligaciones de asistencia familiar', Decimal('7146'))
('Abuso de confianza', Decimal('7089'))
('Despojo', Decimal('7082'))
('Delitos cometidos por servidores publicos', Decimal('4737'))
('Violacion', Decimal('4663'))
('Suplantacion y usurpacion de identidad', Decimal('4579'))
('Otros delitos contra el patrimonio', Decimal('4390'))
('Allanamiento de morada', Decimal('3352'))
('Falsificacion', Decimal('3230'))
('Retencion o sustraccion de menores e incapaces', Decimal('3193'))
('Extorsion', Decimal('2775'))
('Acoso sexual', Decimal('2505'))
('Otros delitos contra la familia', Decimal('2390'))
('Otros delitos que atentan contra la libertad personal', Decimal('2253'))
('Otros delitos que atentan contra la libertad y la seguridad sexual', Decimal('2218'))
('Privacion ilegal de la libertad', Decimal('2145'))
('Otros delitos que atentan contra la vida y la integridad corporal', Decimal('1929'))
('Otros delitos contra la sociedad', Decimal('1735'))
('Violacion a la intimidad sexual', Decimal('1705'))
('Falsedad', Decimal('1203'))
('Delitos contra la administracion de justicia', Decimal('1172'))
('Violencia de genero en todas sus modalidades distinta a la violencia familiar', Decimal('1114'))
('Contra el medio ambiente', Decimal('803'))
('Corrupcion de menores', Decimal('796'))
('Discriminacion', Decimal('791'))
('Hostigamiento sexual', Decimal('668'))
('Tortura', Decimal('597'))
('Feminicidio', Decimal('291'))
('Aborto', Decimal('214'))
('Trata de personas', Decimal('156'))
('Secuestro', Decimal('109'))
('Electorales', Decimal('103'))
('Pornografia infantil', Decimal('83'))
('Evasion de presos', Decimal('55'))
('Rapto', Decimal('7'))
('Incesto', Decimal('1'))
('Trafico de menores', Decimal('0'))

In [ ]:
# Cerrar cursor y conexión
cursor.close()
conexion.close()

In [44]:
## Limpieza y transformación de los datos
#Lee los datos y haz la limpieza de estos a formatos que te resulten más útiles para el posterior análisis.
#Transforma los datos para obtener la siguiente información y darnos una idea de los datos que tenemos:
#(a)  Número promedio de delitos agrupados por municipio y año-mes de ocurrencia de estos.
#(b)  El delito más común por municipio
#(c)  La temporada con más crímenes en México
#(d)  El número promedio de delitos agrupados por tipo de delito y año y mes en la ciudad de México ordenados de mayor a menor
#(e)  Un análisis propio que sea de tu interés.

### Conclusiones