In [1201]:
import pandas as pd

### LIMPIAR DATOS
Se cargan los 5 archivos en un dataframe y se hace una limpieza para cada dataframe

### df_category

In [1202]:
#se carga el archivo DIM_CATEGORY, se normalizan las columnas y se limpian los datos de "\r\n".
df_category = pd.read_csv("DIM_CATEGORY.csv")
df_category['ID_CATEGORY'] = pd.to_numeric(df_category['ID_CATEGORY'])
df_category['CATEGORY'] = df_category['CATEGORY'].str.replace(r"[\r\n]+", " ", regex=True) 
df_category['CATEGORY'] = df_category['CATEGORY'].astype("category")
df_category.info()
df_category.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      category
dtypes: category(1), int64(1)
memory usage: 389.0 bytes

   ID_CATEGORY                     CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                    AIR CARE
2            3                 LAVAVAJILLAS
3            4             MEGA SUPERFICIES
4            5          LAVATORY CARE & BRC

In [1203]:
#se checa si existe valores nulos
df_category.isnull().sum()

ID_CATEGORY    0
CATEGORY       0
dtype: int64

In [1204]:
# se checa si hay renglones duplicados 
df_category.duplicated().sum()
df_category['CATEGORY'].duplicated().sum()

np.int64(0)

### df_fact_sales

In [1205]:
#se carga el archivo FACT_SALES, se normaliza las columnas
df_fact_sales = pd.read_csv("FACT_SALES.csv")
df_fact_sales['TOTAL_UNIT_SALES'] = pd.to_numeric(df_fact_sales['TOTAL_UNIT_SALES'])
df_fact_sales['TOTAL_VALUE_SALES'] = pd.to_numeric(df_fact_sales['TOTAL_VALUE_SALES'])
df_fact_sales['TOTAL_UNIT_AVG_WEEKLY_SALES'] = pd.to_numeric(df_fact_sales['TOTAL_UNIT_AVG_WEEKLY_SALES'])
df_fact_sales['REGION'] = df_fact_sales['REGION'].astype("category")
df_fact_sales.info()
df_fact_sales.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  object
 1   ITEM_CODE                    122002 non-null  object
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  category
dtypes: category(1), float64(3), object(2)
memory usage: 4.8+ MB

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5

In [1206]:
#se calculan estadísticos del dataframe df_fact_sales
df_fact_sales.describe()

       TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES
count     122002.000000      122002.000000                122002.000000
mean           3.211097          90.513761                    10.099904
std           14.496009         350.236505                    22.650142
min            0.000000           0.001000                     0.042000
25%            0.063000           2.662000                     2.316000
50%            0.367000          16.812000                     3.993500
75%            1.520000          62.961500                     8.898000
max          504.681000       12236.759000                   794.000000

In [1207]:
#se checa si hay nulos 
df_fact_sales.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
dtype: int64

### df_calendar

In [1208]:
# se carga el archivo DIM_CALENDAR, se normalizan las columnas
df_calendar = pd.read_excel("DIM_CALENDAR.xlsx")
df_calendar['YEAR'] = pd.to_numeric(df_calendar['YEAR'])
df_calendar['MONTH'] = pd.to_numeric(df_calendar['MONTH'])
df_calendar['WEEK_NUMBER'] = pd.to_numeric(df_calendar['WEEK_NUMBER'])
df_calendar['DATE'] = pd.to_datetime(df_calendar['DATE'])
df_calendar.info()
df_calendar.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ KB

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [1209]:
# se checa si hay renglones duplicados
df_calendar.duplicated().sum()

np.int64(0)

In [1210]:
#se checa si hay valores nulos
df_calendar.isnull().sum()

WEEK           0
YEAR           0
MONTH          0
WEEK_NUMBER    0
DATE           0
dtype: int64

### df_product

In [1211]:
#se carga el archivo DIM_PRODUCT y se normaliza las columnas
df_product = pd.read_excel("DIM_PRODUCT.xlsx")
df_product['CATEGORY'] = pd.to_numeric(df_product['CATEGORY'])
df_product.info()
df_product.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [1212]:
#se checa si hay valores nulos y se encuentra que si hay
df_product.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64

In [1213]:
#se filtra los renglones con los valores nulos
df_product[df_product.isnull().any(axis=1)]

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
33,WHITE MAGIC,WHITE MAGIC,0079893431208,9WHITE MAGIC BOT.PLAS 3970ML IMP 0079893431208,1,LIQUIDO,NaN,CLORO,NaN
107,INDS. ALEN,CLORALEX,7501025401023,CLORALEX EXTRA SENSACION FRUTALES BOT PLAST 95...,1,LIQUIDO,NaN,CLORO,NaN
143,INDS. ALEN,BLANCATEL,7501025402259,BLANCATEL BLANQUEADOR BOTELLA 1.8LT 7501025402259,1,LIQUIDO,NaN,CLORO,NaN
343,CLOROX,CLOROX,7501071901591,CLOROX BLANQUEADOR PARAISO TROPICAL 3800 ML NA...,1,LIQUIDO,NaN,CLORO,NaN
469,OTHERS FABRICANTE UNIF.,OTHERS MARCA UNIF.,7502217411776,KLEEN CLORO BOTELLA 1000 ML NAL 7502217411776,1,LIQUIDO,NaN,CLORO,NaN
495,IBERIA,IBERIA,8411660040503,9IBERIA BLANQUEADOR POLVO 250 GR IMP 841166004...,1,POLVO,NaN,CLORO,NaN
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS

In [1214]:
#se rellenan los valores nulos
df_product.loc[502,"ITEM"] = 1
df_product.iloc[502]

MANUFACTURER                                INDS. ALEN
BRAND                                         CLORALEX
ITEM                                                 1
ITEM_DESCRIPTION    CLORALEX EL RENDIDOR BOT PLAST 2LT
CATEGORY                                             1
FORMAT                                         LIQUIDO
ATTR1                                            CLORO
ATTR2                                            CLORO
ATTR3                                      NO DEFINIDO
Name: 502, dtype: object

In [1215]:
#se rellenan los valores nulos
df_product.loc[503,"ITEM"] = 2
df_product.iloc[503]

MANUFACTURER                                                  CLOROX
BRAND                                                         CLOROX
ITEM                                                               2
ITEM_DESCRIPTION    CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L
CATEGORY                                                           1
FORMAT                                                       LIQUIDO
ATTR1                                                          CLORO
ATTR2                                                          CLORO
ATTR3                                                       MASCOTAS
Name: 503, dtype: object

In [1216]:
#se rellenan los valores nulos
df_product["ATTR1"] = df_product["ATTR1"].fillna("NO DEFINIDO")
df_product["ATTR3"] = df_product["ATTR3"].fillna("NO DEFINIDO")

In [1217]:
#se checa si ya no hay valores nulos
df_product.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                0
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               0
ATTR2               0
ATTR3               0
dtype: int64

In [1218]:
#se checa si hay renglones duplicados
df_product.duplicated().sum()

np.int64(0)

In [1219]:
#se checa si hay duplicados de ITEM
df_product['ITEM'].duplicated().sum()

np.int64(0)

In [1220]:
#se checa los primeros renglones de la tabla df_product
df_product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

### df_segment

In [1221]:
#se carga el archivo DIM_SEGMENT y se normalizan las columnas
df_segment = pd.read_excel("DIM_SEGMENT.xlsx")
df_segment['CATEGORY'] = pd.to_numeric(df_segment['CATEGORY'])
df_segment['SEGMENT'] = df_segment['SEGMENT'].astype("category")
df_segment.info()
df_segment.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     52 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     category
dtypes: category(1), int64(1), object(4)
memory usage: 2.6+ KB

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [1222]:
#se checa si hay renglones duplicados
df_segment.duplicated().sum()

np.int64(0)

In [1223]:
#se checa si hay renglones duplicados
df_segment[df_segment.duplicated(keep=False)]

Empty DataFrame
Columns: [CATEGORY, ATTR1, ATTR2, ATTR3, FORMAT, SEGMENT]
Index: []

In [1224]:
#se checa si hay valores nulos y se encuentra solamente uno
df_segment.isnull().sum()

CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       1
FORMAT      0
SEGMENT     0
dtype: int64

In [1225]:
#se rellena los valores nulos
df_segment["ATTR3"] = df_segment["ATTR3"].fillna("NO DEFINIDO")
df_segment.isnull().sum()

CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       0
FORMAT      0
SEGMENT     0
dtype: int64

In [1226]:
#se checa si hay renglones duplicados y se encuentra uno
df_segment.duplicated().sum()

np.int64(1)

In [1227]:
#se elimina los renglones duplicados
df_segment.drop_duplicates(inplace=True)
df_segment.duplicated().sum()

np.int64(0)

In [1228]:
df_segment.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [1229]:
df_segment['SEGMENT'].unique()

['BLEACH', 'LIQUID & GEL', 'POWDER', 'OTHERS', 'PRETREAT', 'BAR', 'SANITIZER']
Categories (7, object): ['BAR', 'BLEACH', 'LIQUID & GEL', 'OTHERS', 'POWDER', 'PRETREAT', 'SANITIZER']

### UNIÓN DE DATAFRAME
se van a unir las tablas una por una usando los ID o columnas en común.

In [1230]:
df_product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [1231]:
df_fact_sales.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5

In [1232]:
#se hace la union con df_fact_sales y df_product
df_join = df_fact_sales.merge(
    df_product,
    left_on="ITEM_CODE",
    right_on="ITEM",
    how="inner"
)

In [1233]:
df_join.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA

In [1234]:
df_category.head()

   ID_CATEGORY                     CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                    AIR CARE
2            3                 LAVAVAJILLAS
3            4             MEGA SUPERFICIES
4            5          LAVATORY CARE & BRC

In [1235]:
# se hace la unión del resultado de la union anterior con df_category
df_join = df_join.merge(
    df_category,
    left_on="CATEGORY",
    right_on="ID_CATEGORY",
    how="inner"
)

In [1236]:
df_join.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT

In [1237]:
#Se hace la unión del resultado de la unión anterior y el dataframe df_segment
df_join = df_join.merge(
    df_segment,
    left_on=["CATEGORY_x", "ATTR1", "ATTR2", "ATTR3", "FORMAT"],
    right_on=["CATEGORY", "ATTR1", "ATTR2", "ATTR3", "FORMAT"],
    how="inner"
)

In [1238]:
df_join.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y,CATEGORY,SEGMENT
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER

In [1239]:
df_calendar.head()

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [1240]:
#se hace la union del resultado de la unón anterior con df_calendar
df_join = df_join.merge(
    df_calendar,
    on="WEEK",
    how="inner"
)

In [1241]:
df_join.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,...,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y,CATEGORY,SEGMENT,YEAR,MONTH,WEEK_NUMBER,DATE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,...,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER,2022,8,34,2022-08-28
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,...,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER,2022,8,34,2022-08-28
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,...,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER,2022,8,34,2022-08-28
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,...,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER,2022,8,34,2022-08-28
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,...,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT,1,POWDER,2022,8,34,2022-08-28

In [1242]:
#las columnas del dataframe df_join
df_join.columns

Index(['WEEK', 'ITEM_CODE', 'TOTAL_UNIT_SALES', 'TOTAL_VALUE_SALES',
       'TOTAL_UNIT_AVG_WEEKLY_SALES', 'REGION', 'MANUFACTURER', 'BRAND',
       'ITEM', 'ITEM_DESCRIPTION', 'CATEGORY_x', 'FORMAT', 'ATTR1', 'ATTR2',
       'ATTR3', 'ID_CATEGORY', 'CATEGORY_y', 'CATEGORY', 'SEGMENT', 'YEAR',
       'MONTH', 'WEEK_NUMBER', 'DATE'],
      dtype='object')

In [1243]:
#se crean nuevas columnas como la columna del año, mes y año, nombre del mes y precio unitario promedio. Se normaliza el texto del ITEM_DESCRIPTION
import numpy as np
df_join["YEAR"] = df_join['DATE'].dt.year
df_join["YEAR_MONTH"] = df_join["DATE"].dt.to_period("M")
df_join["MONTH_NAME"] = df_join["DATE"].dt.strftime("%b")
df_join["AVG_PRICE_PER_UNIT"] = np.where(
    df_join["TOTAL_UNIT_SALES"] == 0,
    0,
    df_join["TOTAL_VALUE_SALES"] / df_join["TOTAL_UNIT_SALES"]
)
df_join["ITEM_DESCRIPTION"] = df_join["ITEM_DESCRIPTION"].str.upper().str.strip()

df_final=df_join[['DATE','YEAR','YEAR_MONTH','MONTH_NAME','ITEM_CODE','ITEM_DESCRIPTION','CATEGORY','CATEGORY_y','SEGMENT','TOTAL_UNIT_SALES','TOTAL_VALUE_SALES','TOTAL_UNIT_AVG_WEEKLY_SALES','AVG_PRICE_PER_UNIT','REGION']]

In [1244]:
#se cambia el nombre de la columna CATEGORY_y por CATEGORY DESCRIPTION
df_final = df_final.rename(columns={
    "CATEGORY_y": "CATEGORY_DESCRIPTION",
})

In [1245]:
df_final.head()

,DATE,YEAR,YEAR_MONTH,MONTH_NAME,ITEM_CODE,ITEM_DESCRIPTION,CATEGORY,CATEGORY_DESCRIPTION,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,AVG_PRICE_PER_UNIT,REGION
0,2022-08-28,2022,2022-08,Aug,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,FABRIC TREATMENT and SANIT,POWDER,0.006,0.139,1.000,23.166667,TOTAL AUTOS AREA 5
1,2022-08-28,2022,2022-08,Aug,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,FABRIC TREATMENT and SANIT,POWDER,0.487,116.519,2.916,239.258727,TOTAL AUTOS AREA 5
2,2022-08-28,2022,2022-08,Aug,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,FABRIC TREATMENT and SANIT,POWDER,1.391,68.453,5.171,49.211359,TOTAL AUTOS AREA 5
3,2022-08-28,2022,2022-08,Aug,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,FABRIC TREATMENT and SANIT,POWDER,0.022,1.481,1.833,67.318182,TOTAL AUTOS AREA 5
4,2022-08-28,2022,2022-08,Aug,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,FABRIC TREATMENT and SANIT,POWDER,2.037,182.839,5.375,89.758959,TOTAL AUTOS AREA 5

In [1246]:
#se checa cuantos renglones y columnas hay en el dataframe
df_final.shape

(122002, 14)

In [1247]:
df_final.head()

,DATE,YEAR,YEAR_MONTH,MONTH_NAME,ITEM_CODE,ITEM_DESCRIPTION,CATEGORY,CATEGORY_DESCRIPTION,SEGMENT,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,AVG_PRICE_PER_UNIT,REGION
0,2022-08-28,2022,2022-08,Aug,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,FABRIC TREATMENT and SANIT,POWDER,0.006,0.139,1.000,23.166667,TOTAL AUTOS AREA 5
1,2022-08-28,2022,2022-08,Aug,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,FABRIC TREATMENT and SANIT,POWDER,0.487,116.519,2.916,239.258727,TOTAL AUTOS AREA 5
2,2022-08-28,2022,2022-08,Aug,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,FABRIC TREATMENT and SANIT,POWDER,1.391,68.453,5.171,49.211359,TOTAL AUTOS AREA 5
3,2022-08-28,2022,2022-08,Aug,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,FABRIC TREATMENT and SANIT,POWDER,0.022,1.481,1.833,67.318182,TOTAL AUTOS AREA 5
4,2022-08-28,2022,2022-08,Aug,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,FABRIC TREATMENT and SANIT,POWDER,2.037,182.839,5.375,89.758959,TOTAL AUTOS AREA 5

In [1248]:
#se guarda el dataframe en un archivo csv
df_final.to_csv("proyecto.csv", encoding="utf-8-sig", index=False)

In [1255]:
#se agrupan las ventas por YEAR_MONT, CATEGORY y REGION
ventas = df_final.groupby(
    ["YEAR_MONTH", "CATEGORY", "REGION"]
).agg({
    "TOTAL_VALUE_SALES": "sum",
    "TOTAL_UNIT_SALES": "sum"
}).reset_index()

/var/folders/gb/nv8xcn1n2fj8nvh2rrjytk0r0000gn/T/ipykernel_11347/3852004018.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ventas = df_final.groupby(

In [1256]:
ventas

,YEAR_MONTH,CATEGORY,REGION,TOTAL_VALUE_SALES,TOTAL_UNIT_SALES
0,2022-01,1,TOTAL AUTOS AREA 1,34918.239,1361.783
1,2022-01,1,TOTAL AUTOS AREA 2,55395.282,2270.313
2,2022-01,1,TOTAL AUTOS AREA 3,39275.612,1342.147
3,2022-01,1,TOTAL AUTOS AREA 4,34619.625,1334.267
4,2022-01,1,TOTAL AUTOS AREA 5,60595.022,2079.726
...,...,...,...,...,...
128,2023-07,1,TOTAL AUTOS AREA 3,35442.417,1124.875
129,2023-07,1,TOTAL AUTOS AREA 4,29178.904,996.340
130,2023-07,1,TOTAL AUTOS AREA 5,48228.236,1452.995
131,2023-07,1,TOTAL AUTOS AREA 6,41436.356,1518.713
132,2023-07,1,TOTAL AUTOS SCANNING MEXICO,236563.286,8047.364

In [1251]:
# se agrupan las ventas mensuales
ventas_mensuales = df_join.groupby("YEAR_MONTH").agg({
    "TOTAL_VALUE_SALES": "sum",
    "TOTAL_UNIT_SALES": "sum"
}).reset_index()

ventas_mensuales.head()

  YEAR_MONTH  TOTAL_VALUE_SALES  TOTAL_UNIT_SALES
0    2022-01         547832.866         20986.429
1    2022-02         494535.227         18924.671
2    2022-03         510052.354         18707.859
3    2022-04         522004.233         18826.888
4    2022-05         674949.558         24238.346

In [1252]:
#se agrupan las ventas mensuales por categoría
ventas_category_year_month = df_join.groupby(
    ["CATEGORY", "YEAR_MONTH"]
).agg({
    "TOTAL_VALUE_SALES": "sum"
}).reset_index()

ventas_category_year_month.head()

   CATEGORY YEAR_MONTH  TOTAL_VALUE_SALES
0         1    2022-01         547832.866
1         1    2022-02         494535.227
2         1    2022-03         510052.354
3         1    2022-04         522004.233
4         1    2022-05         674949.558

In [1253]:
#se agrupan las ventas por segménto
ventas_segment = df_join.groupby("SEGMENT").agg({
    "TOTAL_VALUE_SALES": "sum"
}).reset_index()

ventas_segment.head()

/var/folders/gb/nv8xcn1n2fj8nvh2rrjytk0r0000gn/T/ipykernel_11347/1310078665.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ventas_segment = df_join.groupby("SEGMENT").agg({

        SEGMENT  TOTAL_VALUE_SALES
0           BAR         243539.230
1        BLEACH        7581283.774
2  LIQUID & GEL        1454056.069
3        OTHERS          15041.415
4        POWDER        1035021.683

In [1254]:
#se agrupan las ventas por region
ventas_region = df_join.groupby("REGION").agg({
    "TOTAL_VALUE_SALES": "sum"
}).reset_index()

ventas_region.head()

/var/folders/gb/nv8xcn1n2fj8nvh2rrjytk0r0000gn/T/ipykernel_11347/1697904046.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ventas_region = df_join.groupby("REGION").agg({

               REGION  TOTAL_VALUE_SALES
0  TOTAL AUTOS AREA 1         714249.979
1  TOTAL AUTOS AREA 2        1188796.150
2  TOTAL AUTOS AREA 3         803655.337
3  TOTAL AUTOS AREA 4         677435.998
4  TOTAL AUTOS AREA 5        1153335.538